- name: Install haproxy package
  yum: 
    name: haproxy
    state: present

- name: Copy haproxy config file
  copy:
    src: haproxy.cfg
    dest: /etc/haproxy/haproxy.cfg
  notify:
  - restartHaproxy

- name: Add iptables rules
  copy:
    src: iptables
    dest: /etc/sysconfig/iptables
  notify:
    - reloadIptables
