- name: Install haproxy package
  yum: 
    name: haproxy
    state: present

- name: Install lighttpd package
  yum:
    name: lighttpd
    state: present

- name: Copy SSL certificate  file
  copy:
    src: twm-selfsigned.pem
    dest: /etc/ssl/certs/twm-selfsigned.pem

- name: Copy haproxy config file
  copy:
    src: haproxy.cfg
    dest: /etc/haproxy/haproxy.cfg
  notify:
  - restartHaproxy

- name: Add iptables rules
  copy:
    src: iptables
    dest: /etc/sysconfig/iptables
  notify:
  - reloadIptables
