- name: Install required packages
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - epel-release
    - python-pip
    - mod_wsgi

- name: Install required python libraries
  pip:
    name: "{{ item }}"
    state: latest
  with_items:
    - pip
    - psycopg2
    - jinja2
    - django-contrib-comments

- name: Install Django 
  pip:
    name: django
    version: 1.11

- name: Create Database for django App
  postgresql_db:
    name: djappsdb
    login_host: localhost
    encoding: UTF8

- name: Configure Database user for django
  postgresql_user:
    db: djappsdb
    name: djadmin
    password: kTV2P7kuG
    priv: ALL

- name: Copy over apache config
  copy: 
    src: theworkingmethodsdotcom.conf
    dest: /etc/httpd/conf.d/theworkingmethodsdotcom.conf
  tags:
  - apache
